name = MultiCraft Game
author = Maksim Gamarnik
description = A basic exploration, mining, crafting and building sandbox game with no NPCs, monsters or animals. MultiCraft Game is usually used with mods added and many mods are available for this game. Reliably maintained by MultiCraft Engine core developers.