-- mods/default/aliases.lua

-- Aliases to support loading worlds using nodes following the old naming convention
-- These can also be helpful when using chat commands, for example /giveme
MultiCraft.register_alias("stone", "default:stone")
MultiCraft.register_alias("stone_with_coal", "default:stone_with_coal")
MultiCraft.register_alias("stone_with_iron", "default:stone_with_iron")
MultiCraft.register_alias("dirt_with_grass", "default:dirt_with_grass")
MultiCraft.register_alias("dirt_with_grass_footsteps", "default:dirt_with_grass_footsteps")
MultiCraft.register_alias("dirt", "default:dirt")
MultiCraft.register_alias("sand", "default:sand")
MultiCraft.register_alias("gravel", "default:gravel")
MultiCraft.register_alias("sandstone", "default:sandstone")
MultiCraft.register_alias("clay", "default:clay")
MultiCraft.register_alias("brick", "default:brick")
MultiCraft.register_alias("tree", "default:tree")
MultiCraft.register_alias("jungletree", "default:jungletree")
MultiCraft.register_alias("junglegrass", "default:junglegrass")
MultiCraft.register_alias("leaves", "default:leaves")
MultiCraft.register_alias("cactus", "default:cactus")
MultiCraft.register_alias("papyrus", "default:papyrus")
MultiCraft.register_alias("bookshelf", "default:bookshelf")
MultiCraft.register_alias("glass", "default:glass")
MultiCraft.register_alias("wooden_fence", "default:fence_wood")
MultiCraft.register_alias("rail", "carts:rail")
MultiCraft.register_alias("ladder", "default:ladder_wood")
MultiCraft.register_alias("wood", "default:wood")
MultiCraft.register_alias("mese", "default:mese")
MultiCraft.register_alias("cloud", "default:cloud")
MultiCraft.register_alias("water_flowing", "default:water_flowing")
MultiCraft.register_alias("water_source", "default:water_source")
MultiCraft.register_alias("lava_flowing", "default:lava_flowing")
MultiCraft.register_alias("lava_source", "default:lava_source")
MultiCraft.register_alias("torch", "default:torch")
MultiCraft.register_alias("sign_wall", "default:sign_wall_wood")
MultiCraft.register_alias("furnace", "default:furnace")
MultiCraft.register_alias("chest", "default:chest")
MultiCraft.register_alias("locked_chest", "default:chest_locked")
MultiCraft.register_alias("cobble", "default:cobble")
MultiCraft.register_alias("mossycobble", "default:mossycobble")
MultiCraft.register_alias("steelblock", "default:steelblock")
MultiCraft.register_alias("sapling", "default:sapling")
MultiCraft.register_alias("apple", "default:apple")

MultiCraft.register_alias("WPick", "default:pick_wood")
MultiCraft.register_alias("STPick", "default:pick_stone")
MultiCraft.register_alias("SteelPick", "default:pick_steel")
MultiCraft.register_alias("MesePick", "default:pick_mese")
MultiCraft.register_alias("WShovel", "default:shovel_wood")
MultiCraft.register_alias("STShovel", "default:shovel_stone")
MultiCraft.register_alias("SteelShovel", "default:shovel_steel")
MultiCraft.register_alias("WAxe", "default:axe_wood")
MultiCraft.register_alias("STAxe", "default:axe_stone")
MultiCraft.register_alias("SteelAxe", "default:axe_steel")
MultiCraft.register_alias("WSword", "default:sword_wood")
MultiCraft.register_alias("STSword", "default:sword_stone")
MultiCraft.register_alias("SteelSword", "default:sword_steel")

MultiCraft.register_alias("Stick", "default:stick")
MultiCraft.register_alias("paper", "default:paper")
MultiCraft.register_alias("book", "default:book")
MultiCraft.register_alias("lump_of_coal", "default:coal_lump")
MultiCraft.register_alias("lump_of_iron", "default:iron_lump")
MultiCraft.register_alias("lump_of_clay", "default:clay_lump")
MultiCraft.register_alias("steel_ingot", "default:steel_ingot")
MultiCraft.register_alias("clay_brick", "default:clay_brick")
MultiCraft.register_alias("snow", "default:snow")

-- 'mese_block' was used for a while for the block form of mese
MultiCraft.register_alias("default:mese_block", "default:mese")

-- Aliases for corrected pine node names
MultiCraft.register_alias("default:pinetree", "default:pine_tree")
MultiCraft.register_alias("default:pinewood", "default:pine_wood")

MultiCraft.register_alias("default:ladder", "default:ladder_wood")
MultiCraft.register_alias("default:sign_wall", "default:sign_wall_wood")
